// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm2AJhgkcqbbKnO_6_bqo8hCuOQlb9O98',
    appId: '1:275699265246:web:1d727d8794b7db53935c4f',
    messagingSenderId: '275699265246',
    projectId: 'merchverse-ca5e5',
    authDomain: 'merchverse-ca5e5.firebaseapp.com',
    storageBucket: 'merchverse-ca5e5.firebasestorage.app',
    measurementId: 'G-GXZKMCQWWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMt4lGAs69YU2eSsDejjn1CKS4BEiCfpA',
    appId: '1:275699265246:android:6e9b744184cd52ac935c4f',
    messagingSenderId: '275699265246',
    projectId: 'merchverse-ca5e5',
    storageBucket: 'merchverse-ca5e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnWtJ0xeNcBgJg1Nyfuz1AJ0U5GAB3lJA',
    appId: '1:275699265246:ios:9eec95a250583dcc935c4f',
    messagingSenderId: '275699265246',
    projectId: 'merchverse-ca5e5',
    storageBucket: 'merchverse-ca5e5.firebasestorage.app',
    iosBundleId: 'com.example.merchverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnWtJ0xeNcBgJg1Nyfuz1AJ0U5GAB3lJA',
    appId: '1:275699265246:ios:9eec95a250583dcc935c4f',
    messagingSenderId: '275699265246',
    projectId: 'merchverse-ca5e5',
    storageBucket: 'merchverse-ca5e5.firebasestorage.app',
    iosBundleId: 'com.example.merchverse',
  );
}
